server:
  port: 10081
spring:
  application:
    name: gateway
eureka:
  instance:
      hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:10080/eureka/
jwt:
  token:
    secret: d3Rvd25hcGk=
    expiration: 1800000
    issuer: chocolatedisco
gateway:
  host: localhost
  token-uri: /gateway/token
  token-header: Authentication

