server:
  port: 10081
spring:
  application:
    name: gateway
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    status-page-url-path: /application/info
    health-check-url-path: /application/health
  client:
    service-url:
      defaultZone: http://127.0.0.1:10080/eureka/
endpoints:
  health:
    id: health
    sensitive: false
    enabled: true
  mappings:
    id: mappings
    sensitive: false
    enabled: true
  info:
    id: info
    sensitive: false
    enabled: true
info:
  app:
    name: API网关
    version: 1.0
zuul:
  host:
    connect-timeout-millis: 60000
jwt:
  token:
    secret: d3Rvd25hcGk=
    expiration: 1800000
    issuer: chocolatedisco
gateway:
  ip-address: 127.0.0.1
  token-uri: /gateway/token
  token-header: Authentication
