server:
  port: @server.port@
spring:
  application:
    name: gateway
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: @spring.datasource.url@
    username: @spring.datasource.username@
    password: @spring.datasource.password@
eureka:
  instance:
    prefer-ip-address: true
    ip-address: @eureka.instance.ip-address@
    status-page-url-path: /application/info
    health-check-url-path: /application/health
  client:
    service-url:
      defaultZone: @eureka.client.service-url.defaultZone@
info:
  app:
    name: API网关
    version: 1.0
zuul:
  host:
    connect-timeout-millis: @zuul.host.connect-timeout-millis@
jwt:
  token:
    secret: @jwt.token.secret@
    expiration: @jwt.token.expiration@
    issuer: @jwt.token.issuer@
gateway:
  ip-address: @eureka.instance.ip-address@
  token-uri: /gateway/token
  token-header: Authentication
  ignores:
