server:
  port: 10081
spring:
  application:
    name: gateway
eureka:
  instance:
      hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:10080/eureka/
endpoints:
  health:
    id: health
    sensitive: false
    enabled: true
  mappings:
    id: mappings
    sensitive: false
    enabled: true
  info:
    id: info
    sensitive: false
    enabled: true
info:
  app:
    name: API网关
    version: 1.0
jwt:
  token:
    secret: d3Rvd25hcGk=
    expiration: 1800000
    issuer: chocolatedisco
gateway:
  host: localhost
  token-uri: /gateway/token
  token-header: Authentication
